# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'R:\Jx4\tools\internal\convert_ui_to_python\releaseNightly_UI.ui'
#
# Created: Thu Jan 19 09:20:56 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(496, 318)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.l_toolsMode = QtGui.QLabel(self.centralwidget)
        self.l_toolsMode.setAlignment(QtCore.Qt.AlignCenter)
        self.l_toolsMode.setObjectName("l_toolsMode")
        self.verticalLayout.addWidget(self.l_toolsMode)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_releaseTools = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_releaseTools.sizePolicy().hasHeightForWidth())
        self.btn_releaseTools.setSizePolicy(sizePolicy)
        self.btn_releaseTools.setObjectName("btn_releaseTools")
        self.horizontalLayout.addWidget(self.btn_releaseTools)
        self.btn_nightlyTools = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_nightlyTools.sizePolicy().hasHeightForWidth())
        self.btn_nightlyTools.setSizePolicy(sizePolicy)
        self.btn_nightlyTools.setObjectName("btn_nightlyTools")
        self.horizontalLayout.addWidget(self.btn_nightlyTools)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.l_rigMode = QtGui.QLabel(self.centralwidget)
        self.l_rigMode.setAlignment(QtCore.Qt.AlignCenter)
        self.l_rigMode.setObjectName("l_rigMode")
        self.verticalLayout.addWidget(self.l_rigMode)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_releaseRig = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_releaseRig.sizePolicy().hasHeightForWidth())
        self.btn_releaseRig.setSizePolicy(sizePolicy)
        self.btn_releaseRig.setObjectName("btn_releaseRig")
        self.horizontalLayout_2.addWidget(self.btn_releaseRig)
        self.btn_nightlyRig = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_nightlyRig.sizePolicy().hasHeightForWidth())
        self.btn_nightlyRig.setSizePolicy(sizePolicy)
        self.btn_nightlyRig.setObjectName("btn_nightlyRig")
        self.horizontalLayout_2.addWidget(self.btn_nightlyRig)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Release Nightly Switcher", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Maya Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.l_toolsMode.setText(QtGui.QApplication.translate("MainWindow", "Tools Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_releaseTools.setText(QtGui.QApplication.translate("MainWindow", "Release", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_nightlyTools.setText(QtGui.QApplication.translate("MainWindow", "Nightly", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Rig / Character", None, QtGui.QApplication.UnicodeUTF8))
        self.l_rigMode.setText(QtGui.QApplication.translate("MainWindow", "Rig Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_releaseRig.setText(QtGui.QApplication.translate("MainWindow", "Release", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_nightlyRig.setText(QtGui.QApplication.translate("MainWindow", "Nightly", None, QtGui.QApplication.UnicodeUTF8))

