# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xmdExportergui.ui'
#
# Created: Tue Dec 15 09:25:30 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_xmdExportWin(object):
    def setupUi(self, xmdExportWin):
        xmdExportWin.setObjectName("xmdExportWin")
        xmdExportWin.resize(800, 800)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(xmdExportWin.sizePolicy().hasHeightForWidth())
        xmdExportWin.setSizePolicy(sizePolicy)
        xmdExportWin.setMinimumSize(QtCore.QSize(800, 692))
        xmdExportWin.setMaximumSize(QtCore.QSize(800, 800))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(96, 81, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(194, 181, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 232, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(96, 81, 72))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(194, 181, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 232, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(194, 181, 155))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 232, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 232, 226))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        xmdExportWin.setPalette(palette)
        xmdExportWin.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(xmdExportWin)
        self.centralwidget.setObjectName("centralwidget")
        self.exportTxt = QtGui.QLabel(self.centralwidget)
        self.exportTxt.setGeometry(QtCore.QRect(10, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.exportTxt.setFont(font)
        self.exportTxt.setScaledContents(False)
        self.exportTxt.setObjectName("exportTxt")
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 160, 781, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.xmdLocTxt = QtGui.QLabel(self.centralwidget)
        self.xmdLocTxt.setGeometry(QtCore.QRect(10, 60, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.xmdLocTxt.setFont(font)
        self.xmdLocTxt.setScaledContents(False)
        self.xmdLocTxt.setObjectName("xmdLocTxt")
        self.curDirBtn = QtGui.QPushButton(self.centralwidget)
        self.curDirBtn.setGeometry(QtCore.QRect(10, 110, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.curDirBtn.setFont(font)
        self.curDirBtn.setStyleSheet("background-color: rgb(165, 152, 126);\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"")
        self.curDirBtn.setObjectName("curDirBtn")
        self.xmdBtn = QtGui.QPushButton(self.centralwidget)
        self.xmdBtn.setGeometry(QtCore.QRect(690, 50, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.xmdBtn.setFont(font)
        self.xmdBtn.setStyleSheet("background-color: rgb(165, 152, 126);\n"
"color: rgb(255, 255, 255);\n"
"border:none")
        self.xmdBtn.setObjectName("xmdBtn")
        self.singleTxt = QtGui.QLabel(self.centralwidget)
        self.singleTxt.setGeometry(QtCore.QRect(10, 390, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.singleTxt.setFont(font)
        self.singleTxt.setScaledContents(False)
        self.singleTxt.setObjectName("singleTxt")
        self.fbxMaBtn = QtGui.QPushButton(self.centralwidget)
        self.fbxMaBtn.setEnabled(True)
        self.fbxMaBtn.setGeometry(QtCore.QRect(690, 450, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.fbxMaBtn.setFont(font)
        self.fbxMaBtn.setAutoFillBackground(False)
        self.fbxMaBtn.setStyleSheet("background-color: rgb(165, 152, 126);\n"
"color: rgb(255, 255, 255);\n"
"border:none")
        self.fbxMaBtn.setObjectName("fbxMaBtn")
        self.fbxMaFileTxt = QtGui.QLabel(self.centralwidget)
        self.fbxMaFileTxt.setGeometry(QtCore.QRect(10, 460, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.fbxMaFileTxt.setFont(font)
        self.fbxMaFileTxt.setScaledContents(False)
        self.fbxMaFileTxt.setObjectName("fbxMaFileTxt")
        self.exportRigBtn = QtGui.QPushButton(self.centralwidget)
        self.exportRigBtn.setGeometry(QtCore.QRect(130, 310, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.exportRigBtn.setFont(font)
        self.exportRigBtn.setStyleSheet("background-color: rgb(165, 152, 126);\n"
"color: rgb(255, 255, 255);\n"
"border:none")
        self.exportRigBtn.setObjectName("exportRigBtn")
        self.exportAnimBtn = QtGui.QPushButton(self.centralwidget)
        self.exportAnimBtn.setGeometry(QtCore.QRect(450, 310, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.exportAnimBtn.setFont(font)
        self.exportAnimBtn.setStyleSheet("background-color: rgb(165, 152, 126);\n"
"color: rgb(255, 255, 255);\n"
"border:none")
        self.exportAnimBtn.setObjectName("exportAnimBtn")
        self.timeTxt = QtGui.QLabel(self.centralwidget)
        self.timeTxt.setGeometry(QtCore.QRect(10, 240, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.timeTxt.setFont(font)
        self.timeTxt.setScaledContents(False)
        self.timeTxt.setObjectName("timeTxt")
        self.dashLine = QtGui.QLabel(self.centralwidget)
        self.dashLine.setGeometry(QtCore.QRect(250, 230, 16, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.dashLine.setFont(font)
        self.dashLine.setScaledContents(False)
        self.dashLine.setObjectName("dashLine")
        self.curRangeBtn = QtGui.QPushButton(self.centralwidget)
        self.curRangeBtn.setGeometry(QtCore.QRect(380, 230, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.curRangeBtn.setFont(font)
        self.curRangeBtn.setStyleSheet("background-color: rgb(165, 152, 126);\n"
"color: rgb(255, 255, 255);\n"
"border:none")
        self.curRangeBtn.setObjectName("curRangeBtn")
        self.animRangeBtn = QtGui.QPushButton(self.centralwidget)
        self.animRangeBtn.setGeometry(QtCore.QRect(570, 230, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.animRangeBtn.setFont(font)
        self.animRangeBtn.setStyleSheet("background-color: rgb(165, 152, 126);\n"
"color: rgb(255, 255, 255);\n"
"border:none")
        self.animRangeBtn.setObjectName("animRangeBtn")
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(10, 560, 781, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.fbxMaDirBtn = QtGui.QPushButton(self.centralwidget)
        self.fbxMaDirBtn.setGeometry(QtCore.QRect(690, 640, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.fbxMaDirBtn.setFont(font)
        self.fbxMaDirBtn.setStyleSheet("background-color: rgb(165, 152, 126);\n"
"color: rgb(255, 255, 255);\n"
"border:none")
        self.fbxMaDirBtn.setObjectName("fbxMaDirBtn")
        self.batchTxt = QtGui.QLabel(self.centralwidget)
        self.batchTxt.setGeometry(QtCore.QRect(10, 580, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.batchTxt.setFont(font)
        self.batchTxt.setScaledContents(False)
        self.batchTxt.setObjectName("batchTxt")
        self.fbxMaDirTxt = QtGui.QLabel(self.centralwidget)
        self.fbxMaDirTxt.setGeometry(QtCore.QRect(10, 650, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.fbxMaDirTxt.setFont(font)
        self.fbxMaDirTxt.setScaledContents(False)
        self.fbxMaDirTxt.setObjectName("fbxMaDirTxt")
        self.batchExportBtn = QtGui.QPushButton(self.centralwidget)
        self.batchExportBtn.setGeometry(QtCore.QRect(290, 710, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.batchExportBtn.setFont(font)
        self.batchExportBtn.setStyleSheet("background-color: rgb(165, 152, 126);\n"
"color: rgb(255, 255, 255);\n"
"border:none")
        self.batchExportBtn.setObjectName("batchExportBtn")
        self.xmdLocFld = QtGui.QLineEdit(self.centralwidget)
        self.xmdLocFld.setGeometry(QtCore.QRect(170, 50, 511, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.xmdLocFld.setFont(font)
        self.xmdLocFld.setStyleSheet("border:none;\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.xmdLocFld.setReadOnly(True)
        self.xmdLocFld.setObjectName("xmdLocFld")
        self.fbxMaFileFld = QtGui.QLineEdit(self.centralwidget)
        self.fbxMaFileFld.setGeometry(QtCore.QRect(160, 450, 511, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.fbxMaFileFld.setFont(font)
        self.fbxMaFileFld.setStyleSheet("border:none;\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.fbxMaFileFld.setReadOnly(True)
        self.fbxMaFileFld.setObjectName("fbxMaFileFld")
        self.fbxMaDirFld = QtGui.QLineEdit(self.centralwidget)
        self.fbxMaDirFld.setGeometry(QtCore.QRect(160, 640, 511, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.fbxMaDirFld.setFont(font)
        self.fbxMaDirFld.setStyleSheet("border:none;\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.fbxMaDirFld.setReadOnly(True)
        self.fbxMaDirFld.setObjectName("fbxMaDirFld")
        self.rangeStartFld = QtGui.QSpinBox(self.centralwidget)
        self.rangeStartFld.setGeometry(QtCore.QRect(140, 230, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.rangeStartFld.setFont(font)
        self.rangeStartFld.setStyleSheet("border:none;\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.rangeStartFld.setAlignment(QtCore.Qt.AlignCenter)
        self.rangeStartFld.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.rangeStartFld.setMaximum(99999999)
        self.rangeStartFld.setObjectName("rangeStartFld")
        self.rangeEndFld = QtGui.QSpinBox(self.centralwidget)
        self.rangeEndFld.setGeometry(QtCore.QRect(270, 230, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.rangeEndFld.setFont(font)
        self.rangeEndFld.setStyleSheet("border:none;\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.rangeEndFld.setAlignment(QtCore.Qt.AlignCenter)
        self.rangeEndFld.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.rangeEndFld.setMaximum(99999999)
        self.rangeEndFld.setProperty("value", 20)
        self.rangeEndFld.setObjectName("rangeEndFld")
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 370, 781, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.curSceneTxt = QtGui.QLabel(self.centralwidget)
        self.curSceneTxt.setGeometry(QtCore.QRect(10, 180, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.curSceneTxt.setFont(font)
        self.curSceneTxt.setScaledContents(False)
        self.curSceneTxt.setObjectName("curSceneTxt")
        self.singleExportBtn = QtGui.QPushButton(self.centralwidget)
        self.singleExportBtn.setGeometry(QtCore.QRect(290, 510, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.singleExportBtn.setFont(font)
        self.singleExportBtn.setStyleSheet("background-color: rgb(165, 152, 126);\n"
"color: rgb(255, 255, 255);\n"
"border:none")
        self.singleExportBtn.setObjectName("singleExportBtn")
        xmdExportWin.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(xmdExportWin)
        self.statusbar.setObjectName("statusbar")
        xmdExportWin.setStatusBar(self.statusbar)

        self.retranslateUi(xmdExportWin)
        QtCore.QMetaObject.connectSlotsByName(xmdExportWin)

    def retranslateUi(self, xmdExportWin):
        xmdExportWin.setWindowTitle(QtGui.QApplication.translate("xmdExportWin", "XMD Exporter", None, QtGui.QApplication.UnicodeUTF8))
        self.exportTxt.setText(QtGui.QApplication.translate("xmdExportWin", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.xmdLocTxt.setText(QtGui.QApplication.translate("xmdExportWin", "XMD Location", None, QtGui.QApplication.UnicodeUTF8))
        self.curDirBtn.setText(QtGui.QApplication.translate("xmdExportWin", "Current Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.xmdBtn.setText(QtGui.QApplication.translate("xmdExportWin", "···", None, QtGui.QApplication.UnicodeUTF8))
        self.singleTxt.setText(QtGui.QApplication.translate("xmdExportWin", "Single", None, QtGui.QApplication.UnicodeUTF8))
        self.fbxMaBtn.setText(QtGui.QApplication.translate("xmdExportWin", "···", None, QtGui.QApplication.UnicodeUTF8))
        self.fbxMaFileTxt.setText(QtGui.QApplication.translate("xmdExportWin", "FBX/MA File", None, QtGui.QApplication.UnicodeUTF8))
        self.exportRigBtn.setText(QtGui.QApplication.translate("xmdExportWin", "Export Rig", None, QtGui.QApplication.UnicodeUTF8))
        self.exportAnimBtn.setText(QtGui.QApplication.translate("xmdExportWin", "Export Animation", None, QtGui.QApplication.UnicodeUTF8))
        self.timeTxt.setText(QtGui.QApplication.translate("xmdExportWin", "Time Range", None, QtGui.QApplication.UnicodeUTF8))
        self.dashLine.setText(QtGui.QApplication.translate("xmdExportWin", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.curRangeBtn.setText(QtGui.QApplication.translate("xmdExportWin", "Current Range", None, QtGui.QApplication.UnicodeUTF8))
        self.animRangeBtn.setText(QtGui.QApplication.translate("xmdExportWin", "Anim Range", None, QtGui.QApplication.UnicodeUTF8))
        self.fbxMaDirBtn.setText(QtGui.QApplication.translate("xmdExportWin", "···", None, QtGui.QApplication.UnicodeUTF8))
        self.batchTxt.setText(QtGui.QApplication.translate("xmdExportWin", "Batch", None, QtGui.QApplication.UnicodeUTF8))
        self.fbxMaDirTxt.setText(QtGui.QApplication.translate("xmdExportWin", "FBX/MA Dir", None, QtGui.QApplication.UnicodeUTF8))
        self.batchExportBtn.setText(QtGui.QApplication.translate("xmdExportWin", "Batch Export", None, QtGui.QApplication.UnicodeUTF8))
        self.curSceneTxt.setText(QtGui.QApplication.translate("xmdExportWin", "Current Scene", None, QtGui.QApplication.UnicodeUTF8))
        self.singleExportBtn.setText(QtGui.QApplication.translate("xmdExportWin", "Export Animation", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    xmdExportWin = QtGui.QMainWindow()
    ui = Ui_xmdExportWin()
    ui.setupUi(xmdExportWin)
    xmdExportWin.show()
    sys.exit(app.exec_())

